export {
  handleHumanShell,
  HUMAN_SHELL_CSS_ROUTE,
  HUMAN_SHELL_DEEP_LINK_ROUTES,
  HUMAN_SHELL_FAVICON_ROUTE,
  HUMAN_SHELL_JS_ROUTE,
  HUMAN_SHELL_LEGACY_FAVICON_ROUTE,
  HUMAN_SHELL_RETURN_PATHS,
  HUMAN_SHELL_ROUTE,
} from "./handler.js";
