import type { DomainPack } from "../types.js";
import { commonFeedbackTypes, unknownAuthority } from "./common.js";
import { potableWaterWorkflowTemplate } from "./municipal-antigua-water.js";

export const municipalAntiguaDomainPack: DomainPack = {
  id: "municipal-antigua",
  name: "Municipal Antigua",
  description: "Antigua Guatemala municipal procedure assistant with national-law and external-reference safeguards.",
  language: "es",
  branding: {
    productName: "LA Muni RAG",
    assistantName: "Asistente Municipal",
    organizationName: "Municipalidad de La Antigua Guatemala",
    primaryLabel: "Antigua-first",
  },
  workflowTypes: [
    { id: "potable_water_project", label: "Agua potable comunitaria", description: "Investigación documental y seguimiento de un proyecto de agua potable para una comunidad.", retrievalHints: [
      "agua potable comunidad solicitud COCODE COMUDE planificación diagnóstico fuente caudal calidad terreno servidumbre topografía hidráulica demanda",
      "PDM-OT POM POA costo financiamiento inversión pública ambiente salud dictámenes Concejo expediente",
      "contratación ofertas adjudicación contrato inicio ejecución supervisión bitácora estimaciones cambios recepción liquidación pagos",
      "operación mantenimiento cierre continuidad calidad del servicio",
    ] },
    { id: "public_works", label: "Obra pública", description: "Construcción, ampliación o mejora municipal.", retrievalHints: ["obra pública proyecto municipal SNIP presupuesto contratación ejecución recepción liquidación"] },
    { id: "procurement", label: "Contratación", description: "Compras, adquisiciones, cotización o licitación.", retrievalHints: ["adquisiciones contrataciones licitación cotización junta contrato obra SNIP"] },
    { id: "project_execution", label: "Ejecución de proyecto", description: "Supervisión, estimaciones y avance de obra.", retrievalHints: ["ejecución obra supervisión estimaciones avance contrato proyecto"] },
    { id: "project_closure", label: "Cierre de obra", description: "Recepción, liquidación y cierre de expediente.", retrievalHints: ["cierre obra recepción final acta recepción liquidación contrato supervisión estimaciones"] },
    { id: "budget", label: "Presupuesto", description: "POM, POA, disponibilidad y ejecución presupuestaria.", retrievalHints: ["presupuesto POA POM asignación obra proyecto municipal"] },
    { id: "community_request", label: "Solicitud comunitaria", description: "Solicitudes comunitarias y priorización local.", retrievalHints: ["COCODE COMUDE comunidad solicitud obra aldea priorización"] },
    { id: "cocode", label: "COCODE", description: "Flujos vinculados a COCODE, COMUDE y comunidades.", retrievalHints: ["COCODE COMUDE comunidad solicitud obra aldea priorización"] },
    { id: "council_approval", label: "Concejo Municipal", description: "Aprobaciones, actas y puntos de Concejo.", retrievalHints: ["Concejo Municipal acta punto aprobación obra contrato presupuesto"] },
    { id: "unknown", label: "Procedimiento no clasificado", description: "Consulta procedimental sin tipo suficiente.", retrievalHints: ["procedimiento municipal requisitos documentos responsables aprobación"] },
  ],
  sourceAuthorityClasses: [
    { id: "external_reference", label: "Referencia externa", description: "Documento de otra municipalidad o entidad no local.", authorityLevel: "comparative", externalReference: true, titleKeywords: ["mixco", "villa nueva", "municipalidad de guatemala"], sourceTypes: [] },
    { id: "national_law", label: "Ley nacional", description: "Norma nacional aplicable.", authorityLevel: "national", titleKeywords: ["ley de contrataciones", "reglamento", "decreto", "katun", "k'atun", "nacional"], sourceTypes: ["law", "decree", "regulation"] },
    { id: "municipal_code", label: "Código Municipal", description: "Código Municipal de Guatemala.", authorityLevel: "national", titleKeywords: ["codigo municipal", "código municipal"], sourceTypes: [] },
    { id: "municipal_manual", label: "Manual municipal", description: "Manual o procedimiento municipal.", authorityLevel: "primary", titleKeywords: ["manual de normas", "procedimiento", "procedimientos", "adquisiciones", "contrataciones"], sourceTypes: ["manual", "procedure"] },
    { id: "mof", label: "MOF", description: "Manual de Organización y Funciones.", authorityLevel: "primary", titleKeywords: ["manual de organizacion", "manual de organización", "mof", "funciones"], sourceTypes: [] },
    { id: "organigram", label: "Organigrama", description: "Estructura organizacional municipal.", authorityLevel: "primary", titleKeywords: ["organigrama"], sourceTypes: [] },
    { id: "pdm_ot", label: "PDM-OT", description: "Plan de Desarrollo Municipal y Ordenamiento Territorial.", authorityLevel: "primary", titleKeywords: ["pdm-ot", "ordenamiento territorial", "plan de desarrollo municipal"], sourceTypes: ["plan"] },
    { id: "pom_poa", label: "POM/POA", description: "Planificación operativa.", authorityLevel: "primary", titleKeywords: ["poa", "pom", "operativo multianual", "operativo anual"], sourceTypes: [] },
    { id: "budget", label: "Presupuesto", description: "Presupuesto o ejecución presupuestaria.", authorityLevel: "primary", titleKeywords: ["presupuesto", "ejecucion presupuestaria", "egresos", "ingresos"], sourceTypes: [] },
    { id: "council_minutes", label: "Actas de Concejo", description: "Actas o puntos de Concejo.", authorityLevel: "primary", titleKeywords: ["acta", "concejo"], sourceTypes: ["council_minutes"] },
    { id: "community_file", label: "Ficha comunitaria", description: "COCODE, COMUDE, comunidad o aldea.", authorityLevel: "context", titleKeywords: ["cocode", "comude", "aldea", "comunidad", "ficha comunitaria"], sourceTypes: [] },
    { id: "case_file", label: "Expediente de caso", description: "Expediente o caso específico.", authorityLevel: "primary", titleKeywords: ["san mateo", "escuela", "expediente", "contrato de obra"], sourceTypes: [] },
    { id: "war_room", label: "War room", description: "Fuente operativa no normativa.", authorityLevel: "context", titleKeywords: ["war room", "banco de propuestas", "kpi", "costos", "metas90"], sourceTypes: [] },
    unknownAuthority,
  ],
  classifierRules: [
    {
      id: "potable-water-community",
      workflowType: "potable_water_project",
      keywords: ["agua potable", "llevar agua", "agua a una comunidad", "abastecimiento de agua", "sistema de agua", "servicio de agua", "proyecto de agua", "red de agua", "agua entubada", "acueducto", "pozo de agua", "captacion de agua"],
      retrievalQueries: [
        "agua potable comunidad solicitud COCODE COMUDE planificación diagnóstico fuente caudal calidad terreno servidumbre topografía hidráulica demanda",
        "PDM-OT POM POA costo financiamiento inversión pública sistema nacional ambiente salud dictámenes Concejo expediente",
        "contratación ofertas adjudicación contrato inicio ejecución supervisión bitácora estimaciones cambios recepción liquidación pagos",
        "operación mantenimiento cierre continuidad calidad del servicio",
      ],
    },
    { id: "closure", workflowType: "project_closure", keywords: ["cierre", "cerrar", "liquidacion", "recepcion final", "acta de recepcion"], retrievalQueries: ["cierre obra recepción final acta recepción liquidación contrato supervisión estimaciones"] },
    { id: "procurement", workflowType: "procurement", keywords: ["licitacion", "cotizacion", "contratacion", "compras", "adquisicion", "adquisiciones"], retrievalQueries: ["adquisiciones contrataciones licitación cotización junta contrato obra SNIP"] },
    { id: "public-works", workflowType: "public_works", keywords: ["construir", "construccion", "estadio", "obra publica", "obra municipal", "escuela", "proyecto snip"], retrievalQueries: ["obra pública proyecto municipal SNIP presupuesto contratación ejecución recepción liquidación"] },
    { id: "execution", workflowType: "project_execution", keywords: ["ejecutar", "ejecucion", "supervision", "estimacion", "avance de obra"], retrievalQueries: ["ejecución obra supervisión estimaciones avance contrato proyecto"] },
    { id: "budget", workflowType: "budget", keywords: ["presupuesto", "poa", "pom", "asignacion", "renglon presupuestario"], retrievalQueries: ["presupuesto POA POM asignación obra proyecto municipal"] },
    { id: "cocode", workflowType: "cocode", keywords: ["cocode", "comude", "comunidad", "aldea", "solicitud comunitaria"], retrievalQueries: ["COCODE COMUDE comunidad solicitud obra aldea priorización"] },
    { id: "council", workflowType: "council_approval", keywords: ["concejo", "acta", "punto de acta", "aprobacion municipal"], retrievalQueries: ["Concejo Municipal acta punto aprobación obra contrato presupuesto"] },
    { id: "generic", workflowType: "unknown", keywords: ["paso", "procedimiento", "flujo", "tramite", "requisito", "documentos"], retrievalQueries: ["procedimiento municipal requisitos documentos responsables aprobación"] },
  ],
  workflowTemplates: [
    potableWaterWorkflowTemplate,
    {
      workflowType: "public_works",
      title: "Flujo procedimental para obra pública municipal",
      defaultSummary: "Encontré evidencia relacionada y organicé un flujo municipal conservador.",
      validationWarning: "Este flujo organiza evidencia documental y no sustituye validación de Gerencia Municipal, DAFIM, Asesoría Jurídica, unidad técnica, Concejo Municipal o COCODE cuando corresponda.",
      steps: [
        { title: "Clasificar el proyecto", action: "Determinar si la iniciativa es obra pública municipal, inversión nueva, ampliación, remodelación, mantenimiento o proyecto sujeto a SNIP u otra planificación aplicable.", requiredDocuments: ["Perfil del proyecto", "Justificación técnica", "Ubicación o terreno", "Necesidad comunitaria o institucional"], outputDocuments: ["Clasificación preliminar del proyecto"], evidencePatterns: ["obra", "proyecto", "snip", "constru"] },
        { title: "Validar planificación y presupuesto", action: "Cruzar la iniciativa con PDM-OT, POM/POA, presupuesto y disponibilidad financiera antes de iniciar contratación.", requiredDocuments: ["PDM-OT", "POM/POA", "Presupuesto", "Disponibilidad presupuestaria"], outputDocuments: ["Validación de alineación y financiamiento"], evidencePatterns: ["pdm", "poa", "pom", "presupuesto", "plan"] },
        { title: "Preparar expediente técnico", action: "Integrar especificaciones, planos, presupuesto detallado, dictámenes y documentos técnicos necesarios para sustentar la obra.", requiredDocuments: ["Especificaciones técnicas", "Planos", "Presupuesto detallado", "Dictamen técnico", "Cronograma"], outputDocuments: ["Expediente técnico de obra"], evidencePatterns: ["tecnico", "técnico", "expediente", "plano", "presupuesto"] },
        { title: "Definir modalidad de contratación", action: "Determinar si corresponde compra directa, cotización, licitación u otra modalidad según monto, objeto y normativa aplicable.", requiredDocuments: ["Monto estimado", "Objeto contractual", "Base normativa", "Disponibilidad presupuestaria"], outputDocuments: ["Modalidad de contratación definida"], evidencePatterns: ["licitacion", "licitación", "cotizacion", "cotización", "contratacion", "adquis"] },
        { title: "Aprobar, contratar y ejecutar", action: "Completar aprobaciones internas, adjudicación/contrato, orden de inicio, supervisión y control de avance según expediente aplicable.", requiredDocuments: ["Bases o términos", "Acta/adjudicación si aplica", "Contrato", "Orden de inicio", "Bitácora o informes de supervisión"], outputDocuments: ["Contrato y expediente de ejecución"], evidencePatterns: ["contrato", "concejo", "acta", "supervision", "ejecucion"] },
        { title: "Recepción, liquidación y cierre", action: "Para cerrar la obra, verificar recepción, informes, pagos, liquidación y documentación final antes de afirmar cierre institucional.", requiredDocuments: ["Acta de recepción", "Informes de supervisión", "Estimaciones/pagos", "Liquidación", "Expediente completo"], outputDocuments: ["Expediente de cierre o liquidación"], evidencePatterns: ["recepcion", "recepción", "liquidacion", "liquidación", "cierre", "estimacion"] },
      ],
    },
    {
      workflowType: "procurement",
      title: "Flujo procedimental para contratación o adquisición municipal",
      defaultSummary: "Organicé un flujo conservador de contratación con evidencia y validación requerida.",
      validationWarning: "Debe validarse contra normativa vigente, expediente y autoridades municipales competentes.",
      steps: [
        { title: "Preparar requerimiento", action: "Definir necesidad, objeto, especificaciones y respaldo presupuestario.", requiredDocuments: ["Solicitud", "Especificaciones técnicas", "Disponibilidad presupuestaria"], outputDocuments: ["Requerimiento completo"], evidencePatterns: ["solicitud", "requerimiento", "presupuesto"] },
        { title: "Definir modalidad", action: "Determinar modalidad de contratación conforme monto, objeto y normativa aplicable.", requiredDocuments: ["Monto", "Objeto", "Normativa aplicable"], outputDocuments: ["Modalidad definida"], evidencePatterns: ["cotizacion", "licitacion", "contratacion", "adquis"] },
        { title: "Integrar expediente y publicar/adjudicar", action: "Preparar bases, integrar junta si aplica, publicar o solicitar ofertas, evaluar y adjudicar.", requiredDocuments: ["Bases", "Junta", "Ofertas", "Actas"], outputDocuments: ["Adjudicación o decisión documentada"], evidencePatterns: ["junta", "bases", "oferta", "adjudic", "acta"] },
        { title: "Formalizar y ejecutar", action: "Formalizar contrato u orden, supervisar cumplimiento y conservar expediente.", requiredDocuments: ["Contrato", "Orden", "Garantías si aplican", "Supervisión"], outputDocuments: ["Contrato ejecutado y expediente"], evidencePatterns: ["contrato", "orden", "garantia", "supervision"] },
      ],
    },
    {
      workflowType: "project_closure",
      title: "Flujo procedimental para cierre y liquidación de obra municipal",
      defaultSummary: "El flujo lista documentos mínimos para validar cierre sin inventar estado actual.",
      validationWarning: "No afirma cierre, recepción ni liquidación sin expediente específico y validación municipal.",
      steps: [
        { title: "Verificar expediente del caso", action: "Localizar el expediente específico antes de afirmar estado actual, recepción o cierre.", requiredDocuments: ["Contrato", "Expediente técnico", "Actas", "Informes de supervisión", "Estimaciones"], outputDocuments: ["Inventario documental del expediente"], evidencePatterns: ["expediente", "contrato", "obra", "escuela", "san mateo"], notes: "Si el expediente específico no está en corpus, el sistema solo puede listar faltantes." },
        { title: "Confirmar recepción física o técnica", action: "Revisar si existe acta de recepción, informe de supervisión o documento equivalente que demuestre entrega de la obra.", requiredDocuments: ["Acta de recepción", "Informe de supervisión", "Evidencia de entrega"], outputDocuments: ["Confirmación documental de recepción"], evidencePatterns: ["recepcion", "recepción", "supervision", "entrega"] },
        { title: "Validar pagos, estimaciones y liquidación", action: "Revisar estimaciones, pagos, saldos, liquidación y cierre administrativo/financiero.", requiredDocuments: ["Estimaciones", "Pagos", "Liquidación", "Presupuesto/ejecución"], outputDocuments: ["Validación financiera de cierre"], evidencePatterns: ["estimacion", "pago", "liquidacion", "presupuesto"] },
        { title: "Confirmar aprobación o conocimiento institucional", action: "Verificar si el cierre requiere punto de Concejo, certificación, intervención de gerencia, unidad técnica o comunidad/COCODE según expediente.", requiredDocuments: ["Acta o punto de Concejo si aplica", "Certificación", "Visto bueno técnico", "Documento comunitario si aplica"], outputDocuments: ["Validación institucional del cierre"], evidencePatterns: ["concejo", "acta", "cocode", "gerencia", "certificacion"] },
      ],
    },
    {
      workflowType: "unknown",
      title: "Flujo procedimental preliminar",
      defaultSummary: "Devuelvo un checklist preliminar porque el tipo de procedimiento no está suficientemente clasificado.",
      validationWarning: "Confirmar fuente aplicable y responsable institucional antes de ejecutar.",
      steps: [
        { title: "Identificar fuente aplicable", action: "Determinar qué documento oficial regula el procedimiento.", requiredDocuments: ["Documento oficial", "Norma aplicable"], outputDocuments: ["Fuente rectora identificada"], evidencePatterns: ["procedimiento", "manual", "norma"] },
        { title: "Listar requisitos", action: "Extraer requisitos, responsables, documentos, plazos y aprobaciones citadas.", requiredDocuments: ["Texto procedimental", "MOF/manual/acta"], outputDocuments: ["Checklist preliminar"], evidencePatterns: ["requisito", "responsable", "plazo"] },
        { title: "Validar con autoridad municipal", action: "Confirmar el flujo con la unidad responsable antes de ejecutarlo.", requiredDocuments: ["Checklist", "Citas", "Expediente"], outputDocuments: ["Flujo validado"], evidencePatterns: ["validacion", "autoridad"] },
      ],
    },
  ],
  governanceRules: [
    { id: "antigua-first", label: "Antigua-first", warning: "Priorizar documentos oficiales de Antigua Guatemala y legislación nacional aplicable." },
    { id: "external-reference", label: "Referencia externa", warning: "Encontré referencia procedimental de otra municipalidad; debe validarse contra documentos oficiales de Antigua Guatemala y normativa nacional aplicable.", appliesToAuthorityClasses: ["external_reference"] },
    { id: "missing-local-source", label: "Falta fuente local", warning: "Sin una fuente oficial local no se debe afirmar que el flujo es obligatorio para Antigua.", appliesWhenNoLocalEvidence: true },
  ],
  feedbackTypes: commonFeedbackTypes,
  exampleQueries: [
    "¿Qué se necesita para llevar agua potable a una comunidad de Antigua Guatemala y cómo se le da seguimiento?",
    "¿Qué hay que hacer para construir un estadio municipal?",
    "¿Qué falta para cerrar la obra de la escuela de San Mateo?",
    "¿Cómo funciona una contratación de obra según un manual externo como Mixco?",
  ],
  evaluationCases: [
    { id: "water-community-procedure", query: "¿Qué se necesita para llevar agua potable a una comunidad de Antigua Guatemala y cómo se le da seguimiento?", expectedWorkflowType: "potable_water_project", notes: "Must compile the Antigua-first 47-category research workflow without treating categories as facts." },
    { id: "stadium-public-works", query: "¿Qué hay que hacer para construir un estadio municipal?", expectedWorkflowType: "public_works", notes: "Must stay Antigua-first." },
    { id: "mixco-external-reference", query: "Usa el manual de Mixco para explicar contratación de obra", expectedWorkflowType: "procurement", expectedAuthorityClass: "external_reference", notes: "Must be comparative only." },
  ],
};
