import { buildCitationLabel } from "../citation.js";
import { contentToText, normalizeWhitespace } from "../normalize.js";
import type { DocumentExtractor, ExtractorInput, NormalizedDocument, NormalizedSection } from "../types.js";
import { IngestionError } from "../types.js";

export interface ExistingPdfSection {
  page?: number;
  section_type?: string;
  section_label?: string;
  section_number?: string;
  title?: string;
  citation_label?: string;
  content?: string;
  content_sha256?: string;
}

export interface ExistingPdfAdapterInput {
  title: string;
  sections: ExistingPdfSection[];
  sourcePath?: string;
  metadata?: Record<string, unknown>;
}

export const normalizeExistingPdfSections = ({
  title,
  sections,
  sourcePath,
  metadata = {},
}: ExistingPdfAdapterInput): NormalizedDocument => {
  const normalizedSections: NormalizedSection[] = sections
    .map((section, index) => {
      const page = typeof section.page === "number" ? section.page : null;
      const heading = section.title ?? section.section_label ?? (page ? `Pagina ${page}` : `Seccion ${index + 1}`);
      const text = normalizeWhitespace(section.content ?? "");

      return {
        heading,
        sectionType: "page" as const,
        sectionPath: [heading],
        text,
        pageStart: page,
        pageEnd: page,
        articleNumber: null,
        citationLabel: section.citation_label ?? buildCitationLabel({ title, heading, pageStart: page }),
        metadata: {
          ordinal: index + 1,
          sourceSectionType: section.section_type ?? null,
          sectionNumber: section.section_number ?? null,
          contentSha256: section.content_sha256 ?? null,
          extractor: "existing_pdf_jsonl_adapter_v1",
        },
      };
    })
    .filter((section) => section.text.length > 0);

  return {
    title,
    sourceFormat: "pdf",
    text: normalizedSections.map((section) => section.text).join("\n\n"),
    sections: normalizedSections,
    metadata: {
      ...metadata,
      sourcePath: sourcePath ?? null,
      extractor: "existing_pdf_jsonl_adapter_v1",
      sourceFlow: "scripts/extract_pdf_sections.py",
    },
  };
};

const parseExistingPdfJsonl = (input: ExtractorInput): ExistingPdfSection[] => {
  const raw = contentToText(input.content);
  try {
    return raw
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line.length > 0)
      .map((line) => JSON.parse(line) as ExistingPdfSection);
  } catch (error) {
    throw new IngestionError(
      "pdf_adapter_invalid_jsonl",
      "pdf",
      "PDF adapter expects JSONL generated by scripts/extract_pdf_sections.py.",
      { cause: error }
    );
  }
};

export const legacyPdfJsonlAdapter: DocumentExtractor = {
  sourceFormat: "pdf",

  extract(input: ExtractorInput): NormalizedDocument {
    return normalizeExistingPdfSections({
      title: input.title,
      sections: parseExistingPdfJsonl(input),
      sourcePath: input.sourcePath,
      metadata: input.metadata,
    });
  },
};
