#!/usr/bin/env python3
"""
Extract one PDF into citable page-level RAG sections.

This script intentionally produces generated artifacts instead of writing to the
database directly. Operators can review the JSONL and SQL before loading them.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Iterable

from pypdf import PdfReader


def sql_literal(value: str | None) -> str:
    if value is None:
        return "NULL"
    cleaned = value.replace("\x00", "").replace("'", "''")
    return f"'{cleaned}'"


def normalize_text(value: str) -> str:
    lines = [line.rstrip() for line in value.replace("\x00", "").splitlines()]
    compact_lines: list[str] = []
    previous_blank = False
    for line in lines:
        blank = not line.strip()
        if blank and previous_blank:
            continue
        compact_lines.append(line)
        previous_blank = blank
    return "\n".join(compact_lines).strip()


def read_pdf_sections(pdf_path: Path) -> tuple[int, list[dict[str, object]]]:
    reader = PdfReader(str(pdf_path))
    sections: list[dict[str, object]] = []
    for index, page in enumerate(reader.pages, start=1):
        text = normalize_text(page.extract_text() or "")
        if not text:
            continue
        content_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()
        sections.append({
            "page": index,
            "section_type": "section",
            "section_label": f"Pagina {index}",
            "section_number": str(index),
            "title": f"Pagina {index}",
            "citation_label": f"PDM-OT Antigua Guatemala, pagina {index}",
            "content": text,
            "content_sha256": content_hash,
        })
    return len(reader.pages), sections


def build_sql(
    *,
    document_title: str,
    version_label: str,
    pdf_page_count: int,
    sections: list[dict[str, object]],
) -> str:
    statements: list[str] = [
        "-- Generated by scripts/extract_pdf_sections.py",
        "-- Review before loading into PostgreSQL.",
        "BEGIN;",
        "",
        "WITH target_version AS (",
        "  SELECT v.id",
        "  FROM rag.document_versions v",
        "  JOIN rag.documents d ON d.id = v.document_id",
        f"  WHERE d.title = {sql_literal(document_title)}",
        f"    AND v.version_label = {sql_literal(version_label)}",
        "  LIMIT 1",
        "), deleted AS (",
        "  DELETE FROM rag.document_sections",
        "  WHERE document_version_id = (SELECT id FROM target_version)",
        "  RETURNING id",
        ")",
        "INSERT INTO rag.document_sections (",
        "  document_version_id,",
        "  section_type,",
        "  section_label,",
        "  section_number,",
        "  title,",
        "  ordinal_path,",
        "  citation_label,",
        "  page_start,",
        "  page_end,",
        "  content,",
        "  content_sha256,",
        "  metadata",
        ")",
    ]

    values: list[str] = []
    for section in sections:
        page = int(section["page"])
        values.append(
            "("
            "(SELECT id FROM target_version), "
            f"{sql_literal(str(section['section_type']))}::rag.section_type, "
            f"{sql_literal(str(section['section_label']))}, "
            f"{sql_literal(str(section['section_number']))}, "
            f"{sql_literal(str(section['title']))}, "
            f"ARRAY[{page}], "
            f"{sql_literal(str(section['citation_label']))}, "
            f"{page}, "
            f"{page}, "
            f"{sql_literal(str(section['content']))}, "
            f"{sql_literal(str(section['content_sha256']))}, "
            f"'{{\"extraction_granularity\":\"page\",\"page\":{page}}}'::jsonb"
            ")"
        )

    statements.append("VALUES")
    statements.append(",\n".join(values))
    statements.append(";")
    statements.extend(
        [
            "",
            "WITH target_version AS (",
            "  SELECT v.id",
            "  FROM rag.document_versions v",
            "  JOIN rag.documents d ON d.id = v.document_id",
            f"  WHERE d.title = {sql_literal(document_title)}",
            f"    AND v.version_label = {sql_literal(version_label)}",
            "  LIMIT 1",
            ")",
            "UPDATE rag.document_versions v",
            "SET",
            f"  page_count = {pdf_page_count},",
            "  extraction_status = 'processed',",
            "  extraction_method = 'pypdf_page_text_v1',",
            "  extracted_at = now(),",
            "  extracted_text_uri = 'artifacts/pdm_ot_sections.jsonl'",
            "FROM target_version",
            "WHERE v.id = target_version.id;",
            "",
            "COMMIT;",
            "",
        ]
    )
    return "\n".join(statements)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pdf", required=True, type=Path)
    parser.add_argument("--jsonl-out", required=True, type=Path)
    parser.add_argument("--sql-out", required=True, type=Path)
    parser.add_argument("--document-title", required=True)
    parser.add_argument("--version-label", required=True)
    args = parser.parse_args()

    pdf_page_count, sections = read_pdf_sections(args.pdf)
    if not sections:
        raise SystemExit(f"No extractable text found in {args.pdf}")

    args.jsonl_out.parent.mkdir(parents=True, exist_ok=True)
    args.sql_out.parent.mkdir(parents=True, exist_ok=True)

    with args.jsonl_out.open("w", encoding="utf-8") as handle:
        for section in sections:
            handle.write(json.dumps(section, ensure_ascii=False) + "\n")

    args.sql_out.write_text(
        build_sql(
            document_title=args.document_title,
            version_label=args.version_label,
            pdf_page_count=pdf_page_count,
            sections=sections,
        ),
        encoding="utf-8",
    )

    print(f"PDF pages: {pdf_page_count}")
    print(f"Extracted {len(sections)} sections")
    print(f"JSONL: {args.jsonl_out}")
    print(f"SQL: {args.sql_out}")


if __name__ == "__main__":
    main()
